few snippets to convert a csv file into a proper list

In [1]:
import csv
with open('C:/RoadCrossingAssistant/Data/labels_secondwise_modified.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)

print(data)

for i in range(len(data)):

    data[i] = [x for n, x in enumerate(data[i]) if any(y != '' for y in data[i][n:])] 

print(data)

[['1', '5', '', '', '', '', '', ''], ['2', '3', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['1', '2', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['1', '4', '', '', '', '', '', ''], ['2', '4', '', '', '', '', '', ''], ['0', '3', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['5', '6', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['5', '6', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['1', '3', '6', '7', '', '', '', ''], ['3', '5', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['2', '4', '5', '7', '', '', '', ''], ['4', '6', '', '', '', '', '', ''], ['2', '6', '', '', '', '', '', ''], ['3', '4', '5', '6', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['2', '4', '5', '6', '', '', '', ''], ['1', '2', '4', '5', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['2',

In [2]:
for i in range(len(data)):
    data[i] =  list(map(int, data[i]))

print(data)

l = [[]]
l.extend(data)
print(l)

[[1, 5], [2, 3], [], [], [1, 2], [], [1, 4], [2, 4], [0, 3], [], [5, 6], [], [5, 6], [], [1, 3, 6, 7], [3, 5], [], [], [2, 4, 5, 7], [4, 6], [2, 6], [3, 4, 5, 6], [], [], [], [2, 4, 5, 6], [1, 2, 4, 5], [], [2, 6], [4, 7], [0, 1, 3, 4], [1, 4], [], [1, 3], [], [], [3, 4], [1, 4, 5, 6], [6, 7], [], [3, 5], [3, 5, 6, 8], [], [2, 3], [], [0, 3], [1, 5], [2, 3, 5, 6], [4, 6], [1, 4], [0, 4], [0, 3, 5, 6], [1, 4], [2, 5], [], [], [1, 6], [0, 1], [0, 2, 4, 6], [1, 4], [0, 1, 2, 4, 5, 6], [0, 6], [0, 2, 3, 5], [1, 2, 4, 5], [0, 3, 4, 6], [0, 4], [1, 2, 4, 5], [2, 4, 5, 6], [4, 6], [], [4, 6], [3, 4], [], [], [0, 7], [6, 9], [0, 1, 6, 10, 12, 16], [0, 1, 4, 6, 8, 9], [9, 10], [0, 3, 5, 8, 11, 14], [0, 3, 12, 15], [6, 10, 11, 13], [3, 5, 8, 11, 19, 21, 22, 26], [1, 4, 5, 7, 9, 15], [1, 6], [0, 1, 3, 4, 7, 9, 14, 15], [0, 2, 5, 8, 14, 16], [6, 8], [4, 5, 12, 14, 17, 18], [0, 2, 13, 14], [12, 13], [0, 1, 2, 5], [10, 11], [1, 2, 9, 10], [1, 2, 10, 13], [0, 5, 9, 12], [], [1, 8, 10, 11], [4, 5, 9, 

In [ ]:
open_file = open('C:/RoadCrossingAssistant/Data/labels_secondwise_modified.pkl', "wb")
pickle.dump(l, open_file)
open_file.close()

open_file = open('C:/RoadCrossingAssistant/Data/labels_secondwise_modified.pkl', "rb")
loaded_list = pickle.load(open_file)
open_file.close()
print(loaded_list)

In [2]:
l = [1,2,3,4,5]
del l[0]
print(l)
l.append(7)
print(l)

[2, 3, 4, 5]
[2, 3, 4, 5, 7]


In [1]:
import numpy as np 
#np.zeros((3,) + (2,) + (2,2,2))

#np.empty((self.batch_size, *self.dim, self.n_channels))
x = np.empty((1, 2, *(4,4), 3))

print(x)

[[[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]]


In [9]:
a = np.zeros((4,4,3))



array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
import tensorflow as tf

C:\Anaconda\envs\roadcross\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Anaconda\envs\roadcross\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Anaconda\envs\roadcross\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Anaconda\envs\roadcross\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarnin

In [8]:
x = np.arange(10).reshape((5,2))
y = np.array([0,1,1,0,0]).reshape((5,1))

dataset = tf.data.Dataset.from_tensor_slices((x,y))

print(dataset)

<DatasetV1Adapter shapes: ((2,), (1,)), types: (tf.int32, tf.int32)>


In [7]:
import cv2
import tensorflow as tf
import numpy as np

frame = cv2.imread("C:/RoadCrossingAssistant/Data/Frames/video33/frame60.jpg")
test_frame = cv2.resize(frame, (480, 270))
test_inp = np.array([test_frame])
print(test_inp.shape)


(1, 270, 480, 3)


In [8]:
model = tf.keras.models.load_model("C:/Users/Siddhi/Desktop/GCET/Project/savedmodels/training_temp")
output = model.predict(test_inp)

print(output[0][0])

0.9999865


In [1]:
 v = "video1"
 frames = 10
 print("showing predictions for {} with total frames {} ".format(v,frames))

showing predictions for video1 with total frames 10 


In [4]:
x = True

for i in range(25):

    if x == True:

        print(i)

        if(i % 2 == 0):

            continue

        print(i)

0
1
1
2
3
3
4
5
5
6
7
7
8
9
9
10
11
11
12
13
13
14
15
15
16
17
17
18
19
19
20
21
21
22
23
23
24
